//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Products_CRUD
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public int id { get; set; }
        public Nullable<int> customer_id { get; set; }
    
        public virtual orderDetail orderDetail { get; set; }
        public virtual order orders1 { get; set; }
        public virtual order order1 { get; set; }
    }
}
